export const GHANA_REGIONS = [
    'Greater Accra',
    'Ashanti',
    'Western',
    'Central',
    'Eastern',
    'Volta',
    'Northern',
    'Upper East',
    'Upper West',
    'Brong-Ahafo',
    'Western North',
    'Ahafo',
    'Bono East',
    'Oti',
    'North East',
    'Savannah',
  ];
  
  export const MAJOR_CITIES: { [key: string]: string[] } = {
    'Greater Accra': [
      'Accra',
      'Tema',
      'Kasoa',
      'Madina',
      'Adenta',
      'Teshie',
      'Nungua',
      'Dansoman',
      'Achimota',
      'East Legon',
    ],
    'Ashanti': [
      'Kumasi',
      'Obuasi',
      'Ejisu',
      'Mampong',
      'Konongo',
      'Bekwai',
      'Offinso',
      'Agogo',
    ],
    'Western': [
      'Sekondi-Takoradi',
      'Tarkwa',
      'Axim',
      'Half Assini',
      'Prestea',
      'Bogoso',
    ],
    'Central': [
      'Cape Coast',
      'Elmina',
      'Winneba',
      'Kasoa',
      'Swedru',
      'Saltpond',
    ],
    'Eastern': [
      'Koforidua',
      'Akosombo',
      'Nkawkaw',
      'Akim Oda',
      'Mpraeso',
      'Begoro',
    ],
    'Volta': [
      'Ho',
      'Hohoe',
      'Keta',
      'Aflao',
      'Denu',
      'Kpando',
    ],
    'Northern': [
      'Tamale',
      'Yendi',
      'Savelugu',
      'Tolon',
      'Gushegu',
    ],
    'Upper East': [
      'Bolgatanga',
      'Navrongo',
      'Bawku',
      'Paga',
    ],
    'Upper West': [
      'Wa',
      'Lawra',
      'Jirapa',
      'Tumu',
    ],
    'Brong-Ahafo': [
      'Sunyani',
      'Techiman',
      'Berekum',
      'Dormaa Ahenkro',
      'Nkoranza',
    ],
  };