export const GHANA_REGIONS = [
    'Greater Accra',
    'Ashanti',
    'Western',
    'Central',
    'Eastern',
    'Volta',
    'Northern',
    'Upper East',
    'Upper West',
    'Western North',
    'Ahafo',
    'Bono',
    'Bono East',
    'Oti',
    'North East',
    'Savannah',
  ];
  
  export const MAJOR_CITIES: { [key: string]: string[] } = {
    'Greater Accra': [
      'Accra',
      'Tema',
      'Kasoa',
      'Madina',
      'Adenta',
      'Teshie',
      'Nungua',
      'Dansoman',
      'Achimota',
      'East Legon',
      'Kokomlemle',
      'Labadi',
      'Osu',
      'Cantonments',
      'Airport Residential',
    ],
    'Ashanti': [
      'Kumasi',
      'Obuasi',
      'Ejisu',
      'Mampong',
      'Konongo',
      'Bekwai',
      'Offinso',
      'Agogo',
      'Ejura',
      'Asante Mampong',
      'Juaso',
      'New Edubiase',
      'Adansi Fomena',
    ],
    'Western': [
      'Sekondi-Takoradi',
      'Tarkwa',
      'Axim',
      'Half Assini',
      'Prestea',
      'Bogoso',
    ],
    'Central': [
      'Cape Coast',
      'Elmina',
      'Winneba',
      'Kasoa',
      'Swedru',
      'Saltpond',
    ],
    'Eastern': [
      'Koforidua',
      'Akosombo',
      'Nkawkaw',
      'Akim Oda',
      'Mpraeso',
      'Begoro',
    ],
    'Volta': [
      'Ho',
      'Hohoe',
      'Keta',
      'Aflao',
      'Denu',
      'Kpando',
    ],
    'Northern': [
      'Tamale',
      'Yendi',
      'Savelugu',
      'Tolon',
      'Gushegu',
    ],
    'Upper East': [
      'Bolgatanga',
      'Navrongo',
      'Bawku',
      'Paga',
    ],
    'Upper West': [
      'Wa',
      'Lawra',
      'Jirapa',
      'Tumu',
    ],
    'Western North': [
      'Sefwi Wiawso',
      'Bibiani',
      'Juaboso',
      'Bodi',
      'Awaso',
    ],
    'Ahafo': [
      'Goaso',
      'Bechem',
      'Hwidiem',
      'Kenyasi',
      'Mim',
    ],
    'Bono': [
      'Sunyani',
      'Berekum',
      'Dormaa Ahenkro',
      'Wenchi',
      'Jaman North',
    ],
    'Bono East': [
      'Techiman',
      'Atebubu',
      'Nkoranza',
      'Kintampo',
      'Prang',
    ],
    'Oti': [
      'Dambai',
      'Kete Krachi',
      'Nkwanta',
      'Krachi East',
      'Krachi West',
    ],
    'North East': [
      'Nalerigu',
      'Gambaga',
      'Walewale',
      'East Mamprusi',
      'West Mamprusi',
    ],
    'Savannah': [
      'Damongo',
      'Bole',
      'Sawla',
      'Tuna',
      'West Gonja',
    ],
  };